/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cepstral_JNICepstral */

#ifndef _Included_cepstral_JNICepstral
#define _Included_cepstral_JNICepstral
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cepstral_JNICepstral
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_initialize
  (JNIEnv *, jobject);

/*
 * Class:     cepstral_JNICepstral
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     cepstral_JNICepstral
 * Method:    cancel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cepstral_JNICepstral_cancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     cepstral_JNICepstral
 * Method:    pauseArticle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_pauseArticle
  (JNIEnv *, jobject);

/*
 * Class:     cepstral_JNICepstral
 * Method:    resumeArticle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_resumeArticle
  (JNIEnv *, jobject);

/*
 * Class:     cepstral_JNICepstral
 * Method:    setVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cepstral_JNICepstral_setVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     cepstral_JNICepstral
 * Method:    setSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cepstral_JNICepstral_setSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     cepstral_JNICepstral
 * Method:    sayArticle
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_sayArticle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cepstral_JNICepstral
 * Method:    isTextPlaying
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_isTextPlaying
  (JNIEnv *, jobject, jint);

/*
 * Class:     cepstral_JNICepstral
 * Method:    stopText
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_stopText
  (JNIEnv *, jobject);

/*
 * Class:     cepstral_JNICepstral
 * Method:    changeVoice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cepstral_JNICepstral_changeVoice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cepstral_JNICepstral
 * Method:    setPitch
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cepstral_JNICepstral_setPitch
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cepstral_JNICepstral
 * Method:    waitTillDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cepstral_JNICepstral_waitTillDone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
